[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "nba-engine-lab"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["src*"]
